"""remove hek_tpm column from the crispr_design table

Revision ID: 14dc4c67ea56
Revises: f033c817cb1c
Create Date: 2021-09-15 16:59:51.615593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14dc4c67ea56'
down_revision = 'f033c817cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crispr_design', 'hek_tpm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'crispr_design',
        sa.Column(
            'hek_tpm',
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
