"""drop the ensg_id column from the uniprot_metadata table

Revision ID: 1f51dcd6d06d
Revises: 872099067902
Create Date: 2022-02-23 19:20:16.425961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f51dcd6d06d'
down_revision = '872099067902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uniprot_metadata', 'ensg_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'uniprot_metadata', sa.Column('ensg_id', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
