"""add columns for gene name and imputed concentration to the abundance_measurement table

Revision ID: 59835c0f5fe6
Revises: 90cfed289034
Create Date: 2022-02-24 11:42:15.907811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59835c0f5fe6'
down_revision = '90cfed289034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abundance_measurement', sa.Column('gene_name', sa.String(), nullable=True))
    op.add_column(
        'abundance_measurement',
        sa.Column('imputed_protein_concentration', sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abundance_measurement', 'imputed_protein_concentration')
    op.drop_column('abundance_measurement', 'gene_name')
    # ### end Alembic commands ###
