"""change the foreign-key constraints on the crispr_design table

Revision ID: 7b75fd399c5e
Revises: efc39d2b08c2
Create Date: 2022-02-22 14:51:16.178065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b75fd399c5e'
down_revision = 'efc39d2b08c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_crispr_design_uniprot_id_uniprot_metadata', 'crispr_design', type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('fk_crispr_design_ensg_id_hgnc_metadata'),
        'crispr_design',
        'hgnc_metadata',
        ['ensg_id'],
        ['ensg_id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_crispr_design_ensg_id_hgnc_metadata'), 'crispr_design', type_='foreignkey'
    )
    op.create_foreign_key(
        'fk_crispr_design_uniprot_id_uniprot_metadata',
        'crispr_design',
        'uniprot_metadata',
        ['uniprot_id'],
        ['uniprot_id'],
    )
    # ### end Alembic commands ###
