"""add ensembl_uniprot_association table and change the primary key of hgnc_metadata to ensg_id

Revision ID: bed48aaf3414
Revises: 208b98134ddd
Create Date: 2022-02-07 19:32:50.150072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed48aaf3414'
down_revision = '208b98134ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_hgnc_metadata_hgnc_id'), 'hgnc_metadata', ['hgnc_id'])

    # drop the existing primary key constraint and column
    op.execute('ALTER TABLE hgnc_metadata DROP CONSTRAINT pk_hgnc_metadata CASCADE')
    op.drop_column('hgnc_metadata', 'id')

    # truncate the table to eliminate duplicated ensg_ids
    op.execute('TRUNCATE TABLE hgnc_metadata')

    # create the new primary key on ensg_id
    op.create_primary_key('pk_hgnc_metadata', 'hgnc_metadata', ['ensg_id'])

    op.create_table(
        'ensembl_uniprot_association',
        sa.Column('ensg_id', sa.String(), nullable=False),
        sa.Column('uniprot_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['ensg_id'],
            ['hgnc_metadata.ensg_id'],
            name=op.f('fk_ensembl_uniprot_association_ensg_id_hgnc_metadata'),
        ),
        sa.PrimaryKeyConstraint(
            'ensg_id', 'uniprot_id', name=op.f('pk_ensembl_uniprot_association')
        ),
    )
    op.create_index(
        op.f('idx_ensembl_uniprot_association_ensg_id'),
        'ensembl_uniprot_association',
        ['ensg_id'],
        unique=False,
    )
    op.create_index(
        op.f('idx_ensembl_uniprot_association_uniprot_id'),
        'ensembl_uniprot_association',
        ['uniprot_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'hgnc_metadata', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_constraint(op.f('uq_hgnc_metadata_hgnc_id'), 'hgnc_metadata', type_='unique')
    op.drop_index(
        op.f('idx_ensembl_uniprot_association_uniprot_id'),
        table_name='ensembl_uniprot_association',
    )
    op.drop_index(
        op.f('idx_ensembl_uniprot_association_ensg_id'), table_name='ensembl_uniprot_association'
    )
    op.drop_table('ensembl_uniprot_association')
    # ### end Alembic commands ###
