"""add uniprotkb_metadata table

Revision ID: efc39d2b08c2
Revises: e2ad4ed1fe94
Create Date: 2022-02-21 18:19:49.137235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efc39d2b08c2'
down_revision = 'e2ad4ed1fe94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'uniprotkb_metadata',
        sa.Column(
            'date_created',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column('primary_uniprot_id', sa.String(), nullable=False),
        sa.Column('secondary_uniprot_ids', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('entry_name', sa.String(), nullable=True),
        sa.Column('gene_name', sa.String(), nullable=True),
        sa.Column('function_comment', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('primary_uniprot_id', name=op.f('pk_uniprotkb_metadata')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uniprotkb_metadata')
    # ### end Alembic commands ###
