"""add protein_abundance table

Revision ID: f033c817cb1c
Revises: 7df168a61e78
Create Date: 2021-09-15 15:05:33.690464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f033c817cb1c'
down_revision = '7df168a61e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'protein_abundance',
        sa.Column(
            'date_created',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column('uniprot_id', sa.String(), nullable=False),
        sa.Column('measured_rna_abundance', sa.Float(), nullable=True),
        sa.Column('measured_protein_abundance', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['uniprot_id'],
            ['uniprot_metadata.uniprot_id'],
            name=op.f('fk_protein_abundance_uniprot_id_uniprot_metadata'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('uniprot_id', name=op.f('pk_protein_abundance')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protein_abundance')
    # ### end Alembic commands ###
